### ISSUE TITLE
Is there any new version for appsettings.json.example or documentation for v2 appsettings.json ?

### ISSUE THREAD

**Issue by krakerz** [Sn0wCrack/saucybot-discord#334]
i just managed to deploy v2 on my local server, and the v2 seems can't get any NSFW pixiv link, it just throw error

```
[2024-11-19 10:23:41 ERR] Exception occured processing or sending messages
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at SaucyBot.Library.Sites.Pixiv.PixivClient.<>c__DisplayClass15_0.<<IllustrationPages>b__0>d.MoveNext() in /src/SaucyBot/Library/Sites/Pixiv/PixivClient.cs:line 105
--- End of stack trace from previous location ---
   at SaucyBot.Services.CacheManager.Remember[T](Object key, Func`1 value) in /src/SaucyBot/Services/CacheManager.cs:line 71
   at SaucyBot.Library.Sites.Pixiv.PixivClient.IllustrationPages(String id) in /src/SaucyBot/Library/Sites/Pixiv/PixivClient.cs:line 105
   at SaucyBot.Site.Pixiv.ProcessImage(IllustrationDetailsResponse illustrationDetails, SocketUserMessage message) in /src/SaucyBot/Site/Pixiv.cs:line 182
   at SaucyBot.Site.Pixiv.Process(Match match, SocketUserMessage message) in /src/SaucyBot/Site/Pixiv.cs:line 55
   at SaucyBot.Services.SiteManager.HandleMessage(SocketUserMessage message) in /src/SaucyBot/Services/SiteManager.cs:line 164
```

some has this error msg too (not NSFW)

```
[2024-11-19 11:02:31 ERR] Exception occured processing or sending messages
System.InvalidOperationException: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.
   at System.Net.Http.HttpClient.PrepareRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at SaucyBot.Library.Sites.Pixiv.PixivClient.PokeFile(String url) in /src/SaucyBot/Library/Sites/Pixiv/PixivClient.cs:line 121
   at SaucyBot.Site.Pixiv.DetermineHighestUsableQualityFile(IEnumerable`1 urls) in /src/SaucyBot/Site/Pixiv.cs:line 231
   at SaucyBot.Site.Pixiv.ProcessImage(IllustrationDetailsResponse illustrationDetails, SocketUserMessage message) in /src/SaucyBot/Site/Pixiv.cs:line 166
   at SaucyBot.Site.Pixiv.Process(Match match, SocketUserMessage message) in /src/SaucyBot/Site/Pixiv.cs:line 55
   at SaucyBot.Services.SiteManager.HandleMessage(SocketUserMessage message) in /src/SaucyBot/Services/SiteManager.cs:line 164
```

i can still fetch it without issue, in v1 though

**Comment by Sn0wCrack** [comment]
I've updated the example configuration files now.

The correct key for the Pixiv Cookie is actually "SessionCookie".
